name: flutter_gemini_ai_mind_quest
description: "Gemini AI MindQuest - A Flutter web app with form submission and Firebase integration."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.0
  
  # State Management - BLoC
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  
  # Firebase
  firebase_core: ^3.8.1
  firebase_database: 11.3.10
  
  # Form Validation
  formz: ^0.7.0
  
  # URL Launcher
  url_launcher: ^6.3.1
  
  # Utilities
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
