# Deploy to Vercel
# This workflow deploys your Next.js app to Vercel
# Vercel supports Server Actions and is perfect for Next.js apps

name: Deploy to Vercel

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          NEXT_PUBLIC_FIREBASE_API_KEY: AIzaSyCSBS4Z-3q1ByVSCwObp6Dw483x13E0A4U
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: mbu-event-ga.firebaseapp.com
          NEXT_PUBLIC_FIREBASE_DATABASE_URL: https://mbu-event-ga-default-rtdb.firebaseio.com
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: mbu-event-ga
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: mbu-event-ga.firebasestorage.app
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: 900766993851
          NEXT_PUBLIC_FIREBASE_APP_ID: 1:900766993851:web:d4b548d51e7a702402489e

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'